### ISSUE TITLE
main/dep11 is not mirrored but requested by apt-get update

### ISSUE THREAD

**Issue by basilgello** [fepitre/debian-snapshot#1]
Dear @fepitre !

Trying to perform a scripted `apt-get update` on the following `/etc/apt/sources.list`:

```
deb [check-valid-until=no] http://debian.notset.fr/snapshot/archive/debian/$SNAPSHOT buster main
deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/$SNAPSHOT buster-updates main
deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/$SNAPSHOT buster-backports main
```

I am stuck at

```
http://debian.notset.fr/snapshot/archive/debian/20210617T212009Z/dists/buster/main/dep11/icons-48x48.tar
```

not mirrored. The `main/dep11` directory is present in `snapshot.debian.org` but absent in the `debian.notset.fr` mirror,

**Comment by fepitre** [comment]
@basilgello thank you for your feedback. I'm filtering most of the metadata needed. I'll add the missing files in the pipeline today or tomorrow. I'll keep you in touch.

**Comment by fepitre** [comment]
@basilgello the mirror for `dep11` content is in progress. It may takes few days.

**Comment by basilgello** [comment]
Great, thanks! In the meantime, I used the `dpkg-divert` workaround https://askubuntu.com/a/880520  to accomplish my task :)
