### ISSUE TITLE
Add 'Contents-all.gz' and 'Contents-amd64.gz'

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#10]
Hello Frédéric,

See the difference between:
http://snapshot.notset.fr/archive/debian/20220111T024807Z/dists/unstable/main/
http://snapshot.debian.org/archive/debian/20220111T024807Z/dists/unstable/main/

Could you also provide `Contents-all.gz` and `Contents-amd64.gz`?
These files are used in the firmware detection for the live-build.

With kind regards,
Roland

**Comment by rclobus** [comment]
Initial description updated to use 'unstable' instead of 'sid'

**Comment by fepitre** [comment]
Sure I'm adding it on my TODO list :)
