### ISSUE TITLE
Add a marker to signify that the sync has not completely finished yet

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#11]
Today an interesting reproducible difference was diagnosed, because the snapshot image was missing the file `InRelease` http://snapshot.notset.fr/archive/debian/20220212T031344Z/dists/sid/ in the first build.

This can be seen in https://jenkins.debian.net/view/live/job/reproducible_debian_live_build_gnome_sid/81/ (until about 2022-02-21)

See also #9 where earlier incomplete snapshots were encountered.

Would it be possible to place a marker file 'not_completely_synced_yet' when you start syncing the repository, and remove that marker file when the last sync run has completed without errors?
Such a marker does not need to be on the dists level, it could also be on the top level.

**Comment by fepitre** [comment]
I think this is still the same problem of retrying the latest snapshot timestamp being common for all suites. Especially, https://github.com/fepitre/debian-snapshot/blob/master/snapshot.py#L690. I need time to figure out the best solution.

**Comment by rclobus** [comment]
So effectively you already nearly have this feature :-)
In `download_release` you download the last 5 files. In the unhappy circumstance of build 81, only one of the files from the final set was missing in the round of `12-Feb-2022 05:21`: `InRelease` came only at `12-Feb-2022 08:04`.
