### ISSUE TITLE
Add support for main/debian-installer

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#12]
Hello Frédéric,

could you add support for another section? The amount of extra bytes is relatively small. These are used by the Debian Installer.

https://snapshot.debian.org/archive/debian/20220223T093842Z/dists/sid/main/debian-installer/binary-amd64/
https://snapshot.notset.fr/archive/debian/20220223T093842Z/dists/unstable/main/debian-installer/binary-amd64/

With kind regards,
Roland

**Comment by rclobus** [comment]
Note: I just wrote a MR for the Debian Installer, https://salsa.debian.org/installer-team/debian-installer/-/merge_requests/27.
I cannot use snapshot.notset.fr yet, but snapshot.debian.org works.

**Comment by fepitre** [comment]
@rclobus what section do you refer to?

**Comment by rclobus** [comment]
The section `main/debian-installer` (similar to `main`, `contrib` and `non-free`). The name is somewhat unusual.

**Comment by fepitre** [comment]
@rclobus I still don't understand. Looking at the two links you provided, the content is similar, there is just not the .xz file. What am I missing?

**Comment by rclobus** [comment]
Hmm. It works now. The request indeed falls back to the .gz file.  I'll close the ticket.
