### ISSUE TITLE
The MR API points to old snapshots

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#17]
Helle Fréderic,

The MR API functions all point to a version of Christmas 2022, though newer snapshots have been generated.
Could you take a look?

With kind regards,
Roland Clobus

https://snapshot.notset.fr/mr/timestamp/debian/latest -> 20221225T204518Z
https://snapshot.notset.fr/mr/timestamp/debian -> 20221225T204518Z
https://snapshot.notset.fr/by-timestamp/debian.txt -> 20230101T091029Z

https://snapshot.debian.org/archive/debian/?year=2023&month=1 -> 20230101T091029Z

**Comment by fepitre** [comment]
Sync is in progress to get data. I don't know what's going on.

**Comment by rclobus** [comment]
Thanks. The newer snapshots are coming in.
