### ISSUE TITLE
Support for inexact timestamps missing

### ISSUE THREAD

**Issue by jan-kiszka** [fepitre/debian-snapshot#2]
With snapshot.debian.org, you can specify http://snapshot.debian.org/archive/debian/20210730T000000Z, and it will take the closest (or the previous?) available timestamp. This seems to be missing from https://debian.notset.fr/snapshot/, making migration or even just a quick tryout harder. Would it be tricky to add such support?

**Comment by fepitre** [comment]
Currently, when you reach `https://debian.notset.fr/snapshot/archive` you reach a simple Nginx endpoint listing directories. I would need to think on how I could wrap this into something that could achieve what you want. Especially, I'm already thinking on how I could expose the filesystem in an intermediary way where I would be able to add some feature like finding the nearest timestamp. As I'm having something working and stable, I will try to think to find a solution.

**Comment by fepitre** [comment]
@jan-kiszka As a temporary workaround, I propose you to use e.g. `http://debian.notset.fr/snapshot/mr/timestamp/debian/20210000T000000Z` which will return you the closest (in the past) timestamp from the one requested. If it exists, it returns the same of course. Could this help?

**Comment by jan-kiszka** [comment]
Is this only an API call, right? Still requires some fiddling to switch existing snapshot.d.o URLs over. But maybe this could also be a building block for a server-side script.

**Comment by fepitre** [comment]
Yes this is an API call to help you getting closest timestamp. Doing so in server side in a robust way needs work that is on the TODO list but I can't do it right now. Currently the main difference with `snapshot.d.o` is that I'm exposing filesystem directly whereas they are exposing only API endpoints that returns directories, files etc., and this is what allows them to create such useful behaviors.
