### ISSUE TITLE
snapshot.notset.fr gives "Bad Gateway"

### ISSUE THREAD

**Issue by safinaskar** [fepitre/debian-snapshot#20]
https://snapshot.notset.fr/ and http://debian.notset.fr/snapshot/archive/debian/ say "502 Bad Gateway"

**Comment by AkihiroSuda** [comment]
@fepitre Could you take a look?

**Comment by fepitre** [comment]
I know what's happening, I notified on IRC that I have hardware failure since end of may. I cannot replace it now, it's on my own pocket.

Mar 13 juin 2023, à 06:13, Akihiro Suda a écrit :

**Comment by Abyss-W4tcher** [comment]
Hello, do you have any news on that ?

**Comment by fepitre** [comment]
I've decided with the Reproducible Builds team that I will stop the current implementation to focus on a newer one but I'll not replace failing hardware. This is an important upcoming work that we wait for fund.

Ven 28 juil 2023, à 14:10, Abyss Watcher a écrit :

**Comment by janjongboom** [comment]
Late kick to this issue, but I'm probably not the only one that will look at this issue to find what happend to the mirror...

I've helped set up a commercial snapshot service that has daily copies of the Ubuntu and Debian package registries (plus some PPAs) - which works exactly the same as snapshot.notset.fr used to work. [Docs](https://docs.stablebuild.com/mirrors-and-caches/os-package-registry-ubuntu-debian-alpine) and [read-only view of the mirror](https://debmirror.stablebuild.com). Realize that this is definitely not for everyone as it's a paid alternative - but running servers and mirrors is expensive, and I'd like to keep my builds reproducible (and mirrors highly available).
