### ISSUE TITLE
Add installer files

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#3]
As discussed on IRC: could you add the installer files? There is (from my part) no need to go back to 2017, starting 'today' is fine.

A sample URL is:
 http://debian.notset.fr/snapshot/archive/debian/20210819T144544Z/dists/bullseye/main/installer-amd64/current/images/cdrom/vmlinuz

All files under /current/images can be downloaded by the live-build script.

For reference: the command that I used is: (based on https://wiki.debian.org/ReproducibleInstalls/LiveImages)
`lb config --apt-http-proxy http://localhost:3142 --parent-mirror-bootstrap http://debian.notset.fr/snapshot/archive/debian/20210819T144544Z --parent-mirror-binary http://debian.notset.fr/snapshot/archive/debian/20210819T144544Z --security false --updates false --apt-options "--yes -o Acquire::Check-Valid-Until=false" --distribution bullseye --debian-installer live --cache-packages false`

**Comment by fepitre** [comment]
I've added it to the sync. For example, getting latest timestamp available https://debian.notset.fr/snapshot/mr/timestamp/debian/latest you reach https://debian.notset.fr/snapshot/archive/debian/20210823T205114Z/dists/unstable/main/installer-amd64/ (or simply replace unstable by bookworm, bullseye or buster. Do you mind to test please to check I've not missed anything else?

**Comment by rclobus** [comment]
Thanks, I like the 'latest' addition to the API.

The file 'vmlinuz' is missing: http://debian.notset.fr/snapshot/archive/debian/20210824T024320Z/dists/bullseye/main/installer-amd64/current/images/cdrom/vmlinuz
see the other location:
http://snapshot.debian.org/archive/debian/20210824T024320Z/dists/bullseye/main/installer-amd64/20210731/images/cdrom/

and also the files vmlinuz and initrd.gz from the gtk subdirectory are not mirrored yet.

**Comment by rclobus** [comment]
Thanks. The next file that is missing:
http://debian.notset.fr/snapshot/archive/debian/20210824T024320Z/dists/bullseye/main/debian-installer/binary-amd64/Packages.gz

**Comment by fepitre** [comment]
Yes it's normal, I'm currently syncing it and another timestamp has been requested to sync before. Doing such add on the fly creates issue...it should be back to the normal soon while it's finished to sync.

**Comment by rclobus** [comment]
I've run the test again, now it needs the udeb files, the first one is:
http://debian.notset.fr/snapshot/archive/debian/20210824T024320Z/pool/main/a/acl/acl-udeb_2.2.53-10_amd64.udeb

**Comment by fepitre** [comment]
@rclobus ok so now if there is no more content to be added (`debian-installer`, `installer-{arch}`, specific `Packages.gz` and `*.udeb` it should be ok.

**Comment by rclobus** [comment]
Thanks. I've been able to create the mini image now. The patch for the Jenkins runs is prepared: https://alioth-lists.debian.net/pipermail/qa-jenkins-dev/Week-of-Mon-20210823/000633.html

**Comment by fepitre** [comment]
Perfect. Any issue appears such as missing content or any other related to your case, please reopen this issue I would do the proper enhancement.
