### ISSUE TITLE
Translations missing for bookworm

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#6]
Hello Frédéric,

I've noticed that the translations are not part of the snapshot service:
http://snapshot.notset.fr/archive/debian/20211121T150414Z/dists/bookworm/main/i18n/Translation-en
This is missing

This was found by Jenkins: https://jenkins.debian.net/view/live/job/reproducible_debian_live_build_standard_bookworm

With kind regards,
Roland

**Comment by fepitre** [comment]
Thank you for the feedback. It looks like `snapshot.d.o` does not provide (anymore) the `.bz2` that I'm syncing for `-en`: http://snapshot.debian.org/archive/debian/20211122T092024Z/dists/bookworm/main/i18n/. I guess I need to adapt for the next syncs.

**Comment by fepitre** [comment]
I've added `-en.xz` to be synced. In case the where `-en.bz2` is not found, at least one translation file should exist. I hope this will solve next runs on your side.

**Comment by rclobus** [comment]
The next Jenkins runs are planned for Sunday.
