### ISSUE TITLE
Add 'sid' in addition to 'unstable'

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#7]
Hello Frédéric,

See:
https://snapshot.notset.fr/archive/debian/20211122T030439Z/dists/
https://snapshot.debian.org/archive/debian/20211122T030439Z/dists/

https://jenkins.debian.net/view/live/job/reproducible_debian_live_build_standard_sid

In the Jenkins tests, I started to use 'sid' instead of 'unstable'. That means that the tests will fail, because on snapshot.notset.fr there is only 'unstable'. The big snapshot server has a symlink to connect 'sid' to 'unstable'.
Would that be something you could/would add?

With kind regards,
Roland

**Comment by fepitre** [comment]
Hello, sure I will try to manage that during the week-end.

**Comment by rclobus** [comment]
Thanks. There is no hurry.
