### ISSUE TITLE
File 'Packages' missing for unstable

### ISSUE THREAD

**Issue by rclobus** [fepitre/debian-snapshot#9]
When building the live images with the latest snapshot, a file was not present of on the snapshot server, which caused the [daily job](https://jenkins.debian.net/view/live/job/reproducible_debian_live_build_smallest-build_sid/21/console) to fail:

[File: Packages](http://snapshot.notset.fr/archive/debian/20211214T030236Z/dists/unstable/main/binary-amd64/Packages)

The parent directory exists and only contains `Releases`

Note: bookworm contains `Packages.gz` [Bookworm](http://snapshot.notset.fr/archive/debian/20211214T030236Z/dists/bookworm/main/binary-amd64/)

**Comment by fepitre** [comment]
Looking at log, it looks like this file was not yet available at the time the snapshot occurred. It should be solved in the hour (the automatic sync occurs every 3 hours) as I'm always rechecking past 12 hours timestamps for such case. I keep it open if something else is happening.

**Comment by fepitre** [comment]
Latest automatic run finished. The "Packages" referred by `apt` is one of `Packages.gz` or `Packages.xz` and it is here now: http://snapshot.notset.fr/archive/debian/20211214T030236Z/dists/unstable/main/binary-amd64/Packages.gz.

**Comment by rclobus** [comment]
I assumed that when a timestamp is mentioned in 'latest', it would mean/guarantee that the snapshot is complete. The timestamp of the Releases.gz file is 07:41, which is several hours newer than the archive snapshot 03:02:36Z

http://snapshot.debian.org/archive/debian/20211214T030236Z/dists/sid/main/binary-amd64/ -> shows 03:02:36Z
http://snapshot.notset.fr/archive/debian/20211214T030236Z/dists/unstable/main/binary-amd64/ -> shows 07:41

The Jenkins job started to run at `Tue Dec 14 05:49:05 UTC 2021` which was between the first sync round and the second one. 
Can you find out why the file was missing? Was it missing from snapshot.d.o in your first sync?

**Comment by fepitre** [comment]
I cannot know what happened...I just see that it did not find the file at the first try. It can be either missing file or issue at downloading the file. I will see what I can do but here the problem is isolating only one dist because of a failure where as the API returns latest timestamp provisioned for other available suites too...

**Comment by rclobus** [comment]
I've found another case:
https://jenkins.debian.net/view/live/job/reproducible_debian_live_build_lxde_sid/27/console which started at `Tue Dec 21 01:05:05 UTC 2021`
`Err:3 http://snapshot.notset.fr/archive/debian/20211220T210437Z unstable/main Translation-en`
which means that it requested `Translation-en.bz2`

But the folder contains:
`Translation-en.bz2                                 21-Dec-2021 02:00      6M`

The next Jenkins job which uses the same snapshot timestamp was https://jenkins.debian.net/view/live/job/reproducible_debian_live_build_cinnamon_sid/28/console, started at `Tue Dec 21 02:06:28 UTC 2021`
`Get:4 http://snapshot.notset.fr/archive/debian/20211220T210437Z unstable/main Translation-en [6642 kB]`
By that time, the second try for the syncing had provided the file.
